# Generated by Django 5.0.3 on 2024-03-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utibu', '0002_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
