# Generated by Django 5.0.3 on 2024-03-31 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utibu', '0003_alter_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermed',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utibu.medicine'),
        ),
    ]
